heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://es01:9200
    - http://es02:9200
    - http://kibana:5601
    - http://example.com

- type: icmp
  schedule: '@every 5s'
  hosts:
    - es01
    - es02
    - kibana
    - 8.8.8.8

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
